#!/usr/bin/env python
# coding: utf-8

# # Intro
# Building a Small Language Model (SLM) from scratch. <br>
# Goal : to generate creative and coherent text based on the input data. <br>
# Using : Tiny stories dataset

# Tried to replicate the SLM training notebook from vizuara <br>
# but some functionalities are not included in the original code <br>
# so don't get confused

# ## Initialize wandb

# In[2]:


# !pip install -q wandb
import wandb
from kaggle_secrets import UserSecretsClient


user_secrets = UserSecretsClient()
my_secret = user_secrets.get_secret("wandb_api_key") 
wandb.login(key=my_secret)


# ## Step 1: Import the Dataset
# 
# TinyStories is a synthetic dataset of short stories that only contain words that a typical 3 to 4-year-olds usually understand, generated by GPT-3.5 and GPT-4. We can get it from HuggingFace.

# In[3]:


# !pip install datasets


# In[4]:


# pip install -U datasets


# In[5]:


from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories")


# In[6]:


ds['train'][0]


# ## Step 2: Tokenize the Dataset
# 
# In this step, we will do the following:
# 
# (1) Tokenize the dataset into tokenIDs.
# 
# (2) Create a file called "train.bin" and "validtion.bin" where we will store the tokenIDs from the entire dataset.
# 
# (3) We make sure the tokenIDs are stored on a disk, rather than on the RAM for efficient computations.

# In[7]:


get_ipython().system('pip install tiktoken')
import tiktoken
import os
import numpy as np
from tqdm.auto import tqdm

enc = tiktoken.get_encoding("gpt2")

# Some functions from https://github.com/karpathy/nanoGPT/blob/master/data/openwebtext/prepare.py

def process(example):
    ids = enc.encode_ordinary(example['text']) # encode_ordinary ignores any special tokens
    out = {'ids': ids, 'len': len(ids)}
    return out

if not os.path.exists("train.bin"):
    tokenized = ds.map(
        process,
        remove_columns=['text'],
        desc="tokenizing the splits",
        num_proc=8,
        )
    # concatenate all ids in each dataset to give one large file for training
    for split, dset in tokenized.items():
        arr_len = np.sum(dset['len'], dtype=np.uint64)
        filename = f'{split}.bin'
        dtype = np.uint16 # (can do since enc.max_token_value == 50256 is < 2**16)
        arr = np.memmap(filename, dtype=dtype, mode='w+', shape=(arr_len,))
        total_batches = 1024

        idx = 0
        for batch_idx in tqdm(range(total_batches), desc=f'writing {filename}'):
            # Batch together samples for faster write
            batch = dset.shard(num_shards=total_batches, index=batch_idx, contiguous=True).with_format('numpy')
            arr_batch = np.concatenate(batch['ids'])
            # Write into mmap
            arr[idx : idx + len(arr_batch)] = arr_batch
            idx += len(arr_batch)
        arr.flush()


# ## Step 3: Create Input-Output batches for the dataset

# In[8]:


# Some functions from https://github.com/karpathy/nanoGPT/blob/master/train.py with slight modifications
#block size = context window
def get_batch(split):
    # We recreate np.memmap every batch to avoid a memory leak, as per
    # https://stackoverflow.com/questions/45132940/numpy-memmap-memory-usage-want-to-iterate-once/61472122#61472122
    if split == 'train':
        data = np.memmap('train.bin', dtype=np.uint16, mode='r')
    else:
        data = np.memmap('validation.bin', dtype=np.uint16, mode='r')
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([torch.from_numpy((data[i:i+block_size]).astype(np.int64)) for i in ix])
    y = torch.stack([torch.from_numpy((data[i+1:i+1+block_size]).astype(np.int64)) for i in ix])
    if device_type == 'cuda':
        # pin arrays x,y, which allows us to move them to GPU asynchronously (non_blocking=True)
        x, y = x.pin_memory().to(device, non_blocking=True), y.pin_memory().to(device, non_blocking=True)
    else:
        x, y = x.to(device), y.to(device)
    return x, y


# ## Step 4: Define the SLM Model Architecture

# In[9]:


import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from dataclasses import dataclass
import numpy as np
from tqdm.auto import tqdm
from contextlib import nullcontext
import os

class LayerNorm(nn.Module):
    def __init__(self, ndim, bias):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(ndim))
        self.bias = nn.Parameter(torch.zeros(ndim)) if bias else None
    def forward(self, x):
        return F.layer_norm(x, self.weight.shape, self.weight, self.bias, 1e-5)

class CausalSelfAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        assert config.n_embd % config.n_head == 0
        self.c_attn = nn.Linear(config.n_embd, 3 * config.n_embd, bias=config.bias)
        self.c_proj = nn.Linear(config.n_embd, config.n_embd, bias=config.bias)
        self.attn_dropout = nn.Dropout(config.dropout)
        self.resid_dropout = nn.Dropout(config.dropout)
        self.n_head = config.n_head
        self.n_embd = config.n_embd
        self.flash = hasattr(F, 'scaled_dot_product_attention')
        if not self.flash:
            self.register_buffer("bias", torch.tril(torch.ones(config.block_size, config.block_size))
                                       .view(1, 1, config.block_size, config.block_size))

    def forward(self, x):
        B, T, C = x.size()
        q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
        k = k.view(B, T, self.n_head, C // self.n_head).transpose(1, 2)
        q = q.view(B, T, self.n_head, C // self.n_head).transpose(1, 2)
        v = v.view(B, T, self.n_head, C // self.n_head).transpose(1, 2)

        if self.flash:
            y = F.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=self.attn_dropout.p if self.training else 0.0, is_causal=True)
        else:
            att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
            att = att.masked_fill(self.bias[:, :, :T, :T] == 0, float('-inf'))
            att = F.softmax(att, dim=-1)
            att = self.attn_dropout(att)
            y = att @ v

        y = y.transpose(1, 2).contiguous().view(B, T, C)
        y = self.resid_dropout(self.c_proj(y))
        return y

class MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.c_fc = nn.Linear(config.n_embd, 4 * config.n_embd, bias=config.bias)
        self.gelu = nn.GELU()
        self.c_proj = nn.Linear(4 * config.n_embd, config.n_embd, bias=config.bias)
        self.dropout = nn.Dropout(config.dropout)
    def forward(self, x):
        return self.dropout(self.c_proj(self.gelu(self.c_fc(x))))

class Block(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.ln1 = LayerNorm(config.n_embd, config.bias)
        self.attn = CausalSelfAttention(config)
        self.ln2 = LayerNorm(config.n_embd, config.bias)
        self.mlp = MLP(config)
    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x

@dataclass
class GPTConfig:
    block_size: int
    vocab_size: int
    n_layer: int
    n_head: int
    n_embd: int
    dropout: float = 0.0
    bias: bool = True

class GPT(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.transformer = nn.ModuleDict(dict(
            wte=nn.Embedding(config.vocab_size, config.n_embd),
            wpe=nn.Embedding(config.block_size, config.n_embd),
            drop=nn.Dropout(config.dropout),
            h=nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
            ln_f=LayerNorm(config.n_embd, config.bias),
        ))
        self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)
        self.transformer.wte.weight = self.lm_head.weight  # weight tying

        self.apply(self._init_weights)
        for pn, p in self.named_parameters():
            if pn.endswith('c_proj.weight'):
                nn.init.normal_(p, mean=0.0, std=0.02 / math.sqrt(2 * config.n_layer))

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        device = idx.device
        b, t = idx.size()
        assert t <= self.config.block_size
        pos = torch.arange(0, t, dtype=torch.long, device=device)

        tok_emb = self.transformer.wte(idx)
        pos_emb = self.transformer.wpe(pos)
        x = self.transformer.drop(tok_emb + pos_emb)
        for block in self.transformer.h:
            x = block(x)
        x = self.transformer.ln_f(x)

        if targets is not None:
            logits = self.lm_head(x)
            loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1), ignore_index=-1)
            return logits, loss
        else:
            logits = self.lm_head(x[:, [-1], :])
            return logits, None

    @torch.no_grad()
    def generate(self, idx, max_new_tokens, temperature=1.0, top_k=None):
        """
        Generate tokens given a conditioning sequence.
        idx: Tensor of shape (B, T)
        """
        for _ in range(max_new_tokens):
            idx_cond = idx if idx.size(1) <= self.config.block_size else idx[:, -self.config.block_size:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :] / temperature
            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = -float('Inf')
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx



# In[10]:


config = GPTConfig(
    vocab_size=50257,     # use the tokenizer's vocab size
    block_size=128,       # or whatever context size you're training with
    n_layer=6,
    n_head=6,
    n_embd=384,
    dropout=0.1,
    bias=True
)

model = GPT(config)


# ## Step 5: Define the loss function

# In[11]:


def estimate_loss(model):
    out = {}
    model.eval()
    with torch.inference_mode():
        for split in ['train', 'val']:
            losses = torch.zeros(eval_iters)
            for k in range(eval_iters):
                X, Y = get_batch(split)
                with ctx:
                    logits, loss = model(X, Y)
                losses[k] = loss.item()
            out[split] = losses.mean()
    model.train()
    return out


# ## Step 6: Define SLM Training Configuration Part 1

# In[12]:


# Training Config
import torch
from contextlib import nullcontext

learning_rate = 1e-4 #more stable training, earlier 1e-4
max_iters = 80000 #increase from 25000 -> 60000 -->> 80000
warmup_steps = 1000 #smoother initial train, earlier 100
min_lr = 5e-4 #lower rate, earlier 5e-4
eval_iters = 500 # increased from 100
batch_size = 32 # changed from 16, better gradient estimate
block_size = 128 #changed from 64, capture longer range dependencies
gradient_accumulation_steps = 32 # reduced from 50


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device_type = 'cuda' if 'cuda' in str(device) else 'cpu' # for later use in torch.autocast
# note: float16 data type will automatically use a GradScaler

# How to use autocast https://wandb.ai/wandb_fc/tips/reports/How-To-Use-Autocast-in-PyTorch--VmlldzoyMTk4NTky
#dtype = 'bfloat16' if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
dtype = 'bfloat16' if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
ptdtype = {'float32': torch.float32, 'bfloat16': torch.bfloat16, 'float16': torch.float16}[dtype]

ctx = nullcontext() if device_type == 'cpu' else torch.amp.autocast(device_type=device_type, dtype=ptdtype)

torch.set_default_device(device)
torch.manual_seed(42)


# ## Step 7: Define SLM Training Configuration Part 2

# In[13]:


from torch.optim.lr_scheduler import LinearLR,SequentialLR, CosineAnnealingLR

##PUT IN WEIGHT DECAY, CHANGED BETA2 to 0.95
optimizer =  torch.optim.AdamW(model.parameters(), lr=learning_rate, betas=(0.9, 0.95), weight_decay=0.1, eps=1e-9) #weight decay for regularization

scheduler_warmup = LinearLR(optimizer, total_iters = warmup_steps) #Implement linear warmup
scheduler_decay = CosineAnnealingLR(optimizer,T_max = max_iters - warmup_steps, eta_min = min_lr) #Implement lr decay
scheduler = SequentialLR(optimizer, schedulers=[scheduler_warmup, scheduler_decay], milestones=[warmup_steps]) #Switching from warmup to decay

# https://stackoverflow.com/questions/72534859/is-gradscaler-necessary-with-mixed-precision-training-with-pytorch
scaler = torch.amp.GradScaler('cuda', enabled=(dtype == 'float16'))


# In[14]:


def save_checkpoint(path, epoch, model, optimizer, scheduler, best_val_loss, train_losses, val_losses):
    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_loss': best_val_loss,
        'train_losses': train_losses,
        'val_losses': val_losses
    }
    torch.save(checkpoint, path)
    print(f"Checkpoint saved to {path}")


# ## Step 8: Pre-train the SLM

# In[15]:


best_model_path = "best_model.pt"
latest_model_path = "latest_model.pt"


# Track training metrics for each epoch
epoch_loss = 0.0
epoch_steps = 0

# Ensure model is on the correct device
model = model.to(device)


# In[16]:


# Initialize variables
start_epoch = 0
best_val_loss = float('inf')
train_loss_list, validation_loss_list = [], []

# Check if we have a checkpoint to resume from
if os.path.exists(best_model_path):
    checkpoint = torch.load(latest_model_path, map_location=torch.device(device))
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_loss = checkpoint['best_val_loss']
    train_loss_list = checkpoint['train_losses']
    validation_loss_list = checkpoint['val_losses']
    print(f"Resuming training from epoch {start_epoch} with best validation loss: {best_val_loss:.4f}")
else:
    start_epoch = 0


# In[17]:


import time

run_name = f"slm-run-{time.strftime('%Y%m%d-%H%M%S')}_kaggle_60k->80k_steps"
wandb.init(
    project="slm-training",  # Project name
    name=run_name,
    config={
        "learning_rate": learning_rate,
        "max_iters": max_iters,
        "warmup_steps": warmup_steps,
        "min_lr": min_lr,
        "batch_size": batch_size,
        "block_size": block_size,
        "gradient_accumulation_steps": gradient_accumulation_steps,
        "n_layer": config.n_layer,
        "n_head": config.n_head,
        "n_embd": config.n_embd,
        "dropout": config.dropout,
    }
)


# In[18]:


# Main training loop
for epoch in tqdm(range(start_epoch, max_iters)):
    # Get batch and train
    X, y = get_batch("train")
    X, y = X.to(device), y.to(device)

    with ctx:
        logits, loss = model(X, y)
        loss_value = loss.item()  # Capture the loss value before division
        loss = loss / gradient_accumulation_steps
        scaler.scale(loss).backward()

    # Track loss for this epoch
    epoch_loss += loss_value
    epoch_steps += 1

    if ((epoch + 1) % gradient_accumulation_steps == 0) or (epoch + 1 == max_iters):
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad(set_to_none=True)

    scheduler.step()

    # Log to wandb every epoch
    wandb.log({
        "epoch": epoch,
        "step_loss": loss_value,
        "learning_rate": optimizer.param_groups[0]['lr'],
        "epoch_avg_loss": epoch_loss / epoch_steps if epoch_steps > 0 else 0,
    })

    # Evaluation and checkpoint saving (less frequently)
    if epoch % eval_iters == 0 and epoch != 0:
        losses = estimate_loss(model)
        train_loss = losses['train'].item()
        val_loss = losses['val'].item()
        print('+'*50)
        print(f"Epoch {epoch}: train loss {train_loss:.4f}, val loss {val_loss:.4f}")
        print(f"The current learning rate: {optimizer.param_groups[0]['lr']:.5f}")

        train_loss_list += [losses['train']]
        validation_loss_list += [losses['val']]

        # Log evaluation metrics
        wandb.log({
            "eval_epoch": epoch,
            "eval_train_loss": train_loss,
            "eval_val_loss": val_loss,
        })

        # Save latest model checkpoint
        save_checkpoint(
            latest_model_path,
            epoch,
            model,
            optimizer,
            scheduler,
            best_val_loss,
            train_loss_list,
            validation_loss_list
        )

        # Save best model checkpoint if validation loss improved
        if losses['val'] < best_val_loss:
            best_val_loss = losses['val']
            save_checkpoint(
                best_model_path,
                epoch,
                model,
                optimizer,
                scheduler,
                best_val_loss,
                train_loss_list,
                validation_loss_list
            )

            # Update best model metrics in wandb
            wandb.run.summary["best_val_loss"] = best_val_loss
            wandb.run.summary["best_epoch"] = epoch

        # Reset epoch tracking metrics
        epoch_loss = 0.0
        epoch_steps = 0


# In[19]:


wandb.log({
    "final_train_loss": train_loss_list[-1].item() if train_loss_list else None,
    "final_val_loss": validation_loss_list[-1].item() if validation_loss_list else None,
    "total_epochs_trained": epoch + 1
})

wandb.run.summary.update({
    "total_epochs": epoch + 1,
    "final_learning_rate": optimizer.param_groups[0]['lr'],
})


# ## Step 9: Plot the SLM Loss Function

# In[20]:


import matplotlib.pyplot as plt
train_loss_list_converted = [i.cpu().detach() for i in train_loss_list]
validation_loss_list_converted = [i.cpu().detach() for i in validation_loss_list]

plt.plot(train_loss_list_converted, 'g', label='train_loss')
plt.plot(validation_loss_list_converted, 'r', label='validation_loss')
plt.xlabel("Steps - Every 100 epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()



# ## Step 10: Run SLM Inference + Evaluation on our trained model

# In[21]:


import math
import nltk
from nltk.translate.bleu_score import sentence_bleu
from collections import Counter

nltk.download('punkt')
nltk.download('punkt_tab')


# In[22]:


# Load the best model
model = GPT(config)  # re-create the model with same config
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
best_model_path = "best_model.pt"

# Load all checkpoint data
checkpoint = torch.load(best_model_path, map_location=torch.device(device))
model.load_state_dict(checkpoint['model_state_dict'])

# Print information about the loaded model
print(f"Loaded model from epoch {checkpoint['epoch']} with validation loss: {checkpoint['best_val_loss']:.4f}")


# In[23]:


def calculate_perplexity(loss):
    return torch.exp(loss)


def compute_diversity(generated_texts):
    all_words = []
    for text in generated_texts:
        all_words.extend(nltk.word_tokenize(text.lower()))

    # Count number of unique words
    unique_words = set(all_words)

    # Compute type-token ratio
    ttr = len(unique_words) / len(all_words) if all_words else 0

    # Compute word distribution and entropy
    word_counts = Counter(all_words)
    total_words = len(all_words)
    entropy = 0

    for word, count in word_counts.items():
        probability = count / total_words
        entropy -= probability * math.log2(probability)

    return {
        "unique_ratio": ttr,
        "num_unique_words": len(unique_words),
        "total_words": len(all_words),
        "entropy": entropy
    }

def evaluate_generated_text(model, prompts, max_new_tokens=100, temperature=0.7):
    model.eval()
    generated_texts = []

    with torch.no_grad():
        for prompt in prompts:
            context = torch.tensor(enc.encode_ordinary(prompt)).unsqueeze(dim=0).to(device)
            generated = model.generate(context, max_new_tokens, temperature=temperature)
            output_text = enc.decode(generated.squeeze().tolist())
            generated_texts.append(output_text)

    diversity_metrics = compute_diversity(generated_texts)

    if 'wandb' in globals():
        for i, (prompt, text) in enumerate(zip(prompts, generated_texts)):
            wandb.log({
                f"example_{i+1}_prompt": prompt,
                f"example_{i+1}_generated": text
            })

        wandb.log({
            "diversity_unique_ratio": diversity_metrics["unique_ratio"],
            "diversity_entropy": diversity_metrics["entropy"]
        })

    return {
        "generated_texts": generated_texts,
        "diversity": diversity_metrics
    }


# In[24]:


evaluation_prompts = [
    "Once upon a time there was",
    "The little girl walked into",
    "A dog and a cat were",
    "In the middle of the night",
    "The sun was shining bright"
]

# Run evaluation
print("Evaluating model generation quality...")
eval_results = evaluate_generated_text(model, evaluation_prompts)

# Print results
print("\nGeneration Diversity Metrics:")
print(f"Unique word ratio: {eval_results['diversity']['unique_ratio']:.4f}")
print(f"Vocabulary size: {eval_results['diversity']['num_unique_words']} unique words")
print(f"Lexical entropy: {eval_results['diversity']['entropy']:.4f}")

# Print generated samples
print("\nGenerated Text Samples:")
for i, (prompt, text) in enumerate(zip(evaluation_prompts, eval_results['generated_texts'])):
    print(f"\nPrompt {i+1}: {prompt}")
    print(f"Generated: {text}")

# Calculate perplexity on validation set
losses = estimate_loss(model)
val_perplexity = calculate_perplexity(losses['val'])
print(f"\nValidation Perplexity: {val_perplexity:.4f}")


# In[25]:


class ONNXWrapper(torch.nn.Module):
    """
    Wrapper to expose a single-tensor forward for ONNX export.
    This returns the logits for the last token as shape (batch_size, vocab_size).
    """
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, input_ids: torch.Tensor):
        # model(input_ids) returns (logits, None) for targets=None
        logits, _ = self.model(input_ids)  # logits shape: (B, 1, V) with your GPT implementation
        # squeeze the time dimension => (B, V)
        return logits.squeeze(1)

def export_to_onnx(model, save_path="slm_model.onnx", opset_version=14, use_last_token=True):
    """
    Export the GPT model to ONNX.
    - model: your GPT instance
    - save_path: output filename
    - opset_version: ONNX opset (14 or higher recommended)
    - use_last_token: when True returns (B, V) logits for last token (recommended for single-step inference).
    """
    # put model in eval and on cpu
    model.eval()
    # turn off "flash" attention to use the masked matmul path (more export-friendly)
    try:
        for block in model.transformer.h:
            if hasattr(block, "attn") and hasattr(block.attn, "flash"):
                block.attn.flash = False
    except Exception:
        # ignore if model structure differs
        pass

    # Wrap model so ONNX export produces a single tensor output
    if use_last_token:
        export_model = ONNXWrapper(model)
        # dummy input: shape (batch_size=1, seq_len=1) or longer if you want export to accept variable sequence lengths
        dummy_input = torch.zeros(1, 1, dtype=torch.long, device="cpu")
        output_names = ["logits"]  # shape (B, V)
        dynamic_axes = {
            "input": {0: "batch_size", 1: "sequence"},
            "logits": {0: "batch_size", 1: "vocab_size"},
        }
    else:
        # if you prefer full-sequence logits (B, T, V), implement a wrapper that returns full sequence logits
        class FullSeqWrapper(torch.nn.Module):
            def __init__(self, model): 
                super().__init__(); self.model = model
            def forward(self, input_ids):
                logits, _ = self.model(input_ids)  # expected (B, T, V)
                return logits
        export_model = FullSeqWrapper(model)
        dummy_input = torch.zeros(1, 4, dtype=torch.long, device="cpu")  # example T=4
        output_names = ["logits"]
        dynamic_axes = {
            "input": {0: "batch_size", 1: "sequence"},
            "logits": {0: "batch_size", 1: "sequence", 2: "vocab_size"},
        }

    # Move wrapper to CPU
    export_model.to("cpu")
    dummy_input = dummy_input.to("cpu")

    # Export
    torch.onnx.export(
        export_model,               # model being exported
        dummy_input,               # example input
        save_path,                 # where to save
        export_params=True,        # store parameters
        opset_version=opset_version,
        do_constant_folding=True,
        input_names=["input"],
        output_names=output_names,
        dynamic_axes=dynamic_axes,
        verbose=False
    )
    print(f"Model exported to {save_path}")


# In[26]:


try:
    export_to_onnx(model)
except Exception as e:
    print(f"Error exporting model to ONNX: {e}")


# In[27]:


wandb.finish()

